<?php

/**
 * Implements \hook_mail().
 *
 * This is intentionally minimal to avoid using the static \Drupal object and so
 * only forwards data from the $params array to $message.
 *
 * @see \Drupal\omnipedia_logger\Logger\Handler\DrupalMailHandler
 */
function omnipedia_logger_mail(
  string $key, array &$message, array $params
): void {

  $message['subject'] = $params['subject'];
  $message['body'][]  = $params['body'];

}
